name = "cloudtools-api"
workers_dev = true
compatibility_date = "2026-04-01"
compatibility_flags = ["nodejs_compat"]
main = "index.js"

[[d1_databases]]
binding = "DB"
database_name = "cloudtools-db"
database_id = "dab6dfc3-afa9-45a1-804a-bc88826b2216"

[[kv_namespaces]]
binding = "KV"
id = "e772c86938114c23a7badd865fe299a8"
preview_id = "e772c86938114c23a7badd865fe299a8"
